const notifications = [
  {
    id: 1,
    title: 'New Message',
    message: 'You have received a new message from John Doe.',
    timestamp: new Date('2023-10-01T10:30:00Z'),
    isRead: false,
  },
  {
    id: 2,
    title: 'System Update',
    message: 'A new system update is available. Please update your application.',
    timestamp: new Date('2023-10-02T12:00:00Z'),
    isRead: false,
  },
  {
    id: 3,
    title: 'Reminder',
    message: 'Don’t forget to submit your report by the end of the week.',
    timestamp: new Date('2023-10-03T09:00:00Z'),
    isRead: true,
  },
  {
    id: 4,
    title: 'New Comment',
    message: 'Someone commented on your post.',
    timestamp: new Date('2023-10-04T15:45:00Z'),
    isRead: false,
  },
  {
    id: 5,
    title: 'Friend Request',
    message: 'You have a new friend request from Jane Smith.',
    timestamp: new Date('2023-10-05T08:15:00Z'),
    isRead: true,
  },
    {
    id: 6,
    title: 'New Message',
    message: 'You have received a new message from John Doe.',
    timestamp: new Date('2023-10-01T10:30:00Z'),
    isRead: false,
  },
  {
    id: 7,
    title: 'System Update',
    message: 'A new system update is available. Please update your application.',
    timestamp: new Date('2023-10-02T12:00:00Z'),
    isRead: false,
  },
  {
    id: 8,
    title: 'Reminder',
    message: 'Don’t forget to submit your report by the end of the week.',
    timestamp: new Date('2023-10-03T09:00:00Z'),
    isRead: true,
  },
  {
    id: 9,
    title: 'New Comment',
    message: 'Someone commented on your post.',
    timestamp: new Date('2023-10-04T15:45:00Z'),
    isRead: false,
  },
  {
    id: 10,
    title: 'Friend Request',
    message: 'You have a new friend request from Jane Smith.',
    timestamp: new Date('2023-10-05T08:15:00Z'),
    isRead: true,
  },
    {
    id: 11,
    title: 'New Message',
    message: 'You have received a new message from John Doe.',
    timestamp: new Date('2023-10-01T10:30:00Z'),
    isRead: false,
  },
  {
    id: 12,
    title: 'System Update',
    message: 'A new system update is available. Please update your application.',
    timestamp: new Date('2023-10-02T12:00:00Z'),
    isRead: false,
  },
  {
    id: 13,
    title: 'Reminder',
    message: 'Don’t forget to submit your report by the end of the week.',
    timestamp: new Date('2023-10-03T09:00:00Z'),
    isRead: true,
  },
  {
    id: 14,
    title: 'New Comment',
    message: 'Someone commented on your post.',
    timestamp: new Date('2023-10-04T15:45:00Z'),
    isRead: false,
  },
  {
    id: 15,
    title: 'Friend Request',
    message: 'You have a new friend request from Jane Smith.',
    timestamp: new Date('2023-10-05T08:15:00Z'),
    isRead: true,
  },
];

export default notifications;
